namespace: probability
TRANSIT_PROBABILITY:
  price_up:
    price_down: 0.45
    price_up: 0.23
    price_keep: 0.32
  price_keep:
    price_up: 0.27
    price_keep: 0.32
    price_down: 0.41
  price_down:
    price_down: 0.26
    price_keep: 0.38
    price_up: 0.36

emission_probability:
  price_up:
    ds_increase: 0.584
    ds_decrease: 0.416
  price_keep:
    ds_increase: 0.52
    ds_decrease: 0.48
  price_down:
    ds_increase: 0.34
    ds_decrease: 0.66